name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact_name: metronome-windows
            binary_name: MetronomeApp.exe

          - os: macos-latest
            artifact_name: metronome-macos
            binary_name: MetronomeApp

          - os: ubuntu-latest
            artifact_name: metronome-linux
            binary_name: MetronomeApp

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        working-directory: MetronomeApp
        run: cargo build --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: MetronomeApp/target/release/${{ matrix.binary_name }}

  github-release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*